"""Cross-harness patch bundler.

MVP exports: Claude Code SKILL.md. The contract is stable so Cursor / LangGraph /
LobeHub / OpenClaw targets slot in with one function each.
"""
from __future__ import annotations

import hashlib
from typing import Iterable, List

from .models import (
    BundleArtefact,
    BundleTarget,
    PatchStatus,
    ResourcePatch,
    ResourceScheme,
)


class Bundler:
    def supported_targets(self) -> List[BundleTarget]:
        return [BundleTarget.CLAUDE_CODE]

    def bundle(
        self,
        patch: ResourcePatch,
        targets: Iterable[BundleTarget],
    ) -> List[BundleArtefact]:
        if patch.status != PatchStatus.COMMITTED:
            raise ValueError("only committed patches can be bundled")
        out: List[BundleArtefact] = []
        for t in targets:
            if t == BundleTarget.CLAUDE_CODE:
                out.append(_to_claude_code(patch))
            else:
                raise NotImplementedError(f"target not implemented in MVP: {t.value}")
        return out


def _checksum(content: str) -> str:
    return hashlib.sha256(content.encode()).hexdigest()[:16]


def _to_claude_code(patch: ResourcePatch) -> BundleArtefact:
    if patch.resource_uri.scheme != ResourceScheme.SKILL:
        raise NotImplementedError(
            f"Claude Code target only supports skill:// resources in MVP "
            f"(got {patch.resource_uri.scheme.value})"
        )
    name = patch.resource_uri.name
    triggers = patch.diff.get("triggers", [])
    rev_note = patch.diff.get("revision_note", "auto-generated by gnomon")
    content = (
        "---\n"
        f"name: {name}\n"
        f"description: skill evolved by gnomon (patch {patch.patch_id})\n"
        "source: gnomon-evolved\n"
        f"patch_id: {patch.patch_id}\n"
        f"attribution_source: {patch.attribution_source}\n"
        "---\n\n"
        "## When to use\n\n"
        + "".join(f"- {t}\n" for t in triggers)
        + "\n"
        "## Revision note\n\n"
        f"{rev_note}\n"
    )
    return BundleArtefact(
        target=BundleTarget.CLAUDE_CODE,
        filename=f"{name}.md",
        content=content,
        checksum=_checksum(content),
    )
